#!/bin/bash
# crosscheck installer.
#
# Two things get installed, and they are deliberately separate:
#
#   1. ~/.local/bin/cc  - a launcher STUB on the main disk. The suite itself
#      stays on /Volumes/T7 (repos live on the external drive, always), but the
#      stub does not, so when T7 is unmounted you get one clear sentence
#      instead of a stack trace from a skill trigger. 💀
#
#   2. an optional per-repo git pre-push hook. This is the part that matters:
#      a rule that lives only in a SKILL.md is text somebody has to remember,
#      and the mining pass found exactly that failure mode - a documented gate
#      wired nowhere and therefore never run. A hook fires whether or not
#      anyone remembers it.
#
# usage:
#   ./install.sh                 # install the cc launcher
#   ./install.sh --hook <repo>   # also install pre-push in <repo>
#   ./install.sh --uninstall     # remove the launcher

set -euo pipefail

SUITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${CROSSCHECK_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/cc"

uninstall() {
  rm -f "$LAUNCHER"
  echo "removed $LAUNCHER"
  exit 0
}

install_launcher() {
  mkdir -p "$BIN_DIR"
  cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# crosscheck launcher (generated by install.sh - edit the suite, not this file)
SUITE="$SUITE_DIR/crosscheck.py"
if [ ! -f "\$SUITE" ]; then
  echo "crosscheck: suite not found at \$SUITE" >&2
  echo "  the drive holding it is probably not mounted. mount it and retry." >&2
  # exit 3 = INVALID: could not evaluate. never 0, which would read as clean.
  exit 3
fi
exec python3 "\$SUITE" "\$@"
LAUNCH
  chmod +x "$LAUNCHER"
  echo "installed $LAUNCHER -> $SUITE_DIR/crosscheck.py"
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "NOTE: $BIN_DIR is not on your PATH. add it:"
       echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc" ;;
  esac
}

install_hook() {
  local repo="$1"
  [ -d "$repo/.git" ] || { echo "not a git repo: $repo" >&2; exit 1; }
  local hook="$repo/.git/hooks/pre-push"
  if [ -e "$hook" ]; then
    echo "pre-push already exists in $repo - not overwriting. merge by hand:" >&2
    echo "  $hook" >&2
    exit 1
  fi
  cat > "$hook" <<'HOOK'
#!/bin/bash
# crosscheck pre-push: the branch-shape check, before it costs you a PR.
# Catches the stale-branch-rebase that replays other people's commits.
# Bypass deliberately with:  git push --no-verify
CC="$(command -v cc || true)"
[ -z "$CC" ] && exit 0   # not installed here: do not block a push
"$CC" pr-branch "$(git rev-parse --show-toplevel)"
code=$?
# 2 = FINDING, 3 = INVALID. Both stop the push; 4 (judgment) and 0 do not.
if [ "$code" = "2" ] || [ "$code" = "3" ]; then
  echo ""
  echo "crosscheck blocked this push. fix it, or: git push --no-verify"
  exit 1
fi
exit 0
HOOK
  chmod +x "$hook"
  echo "installed pre-push hook in $repo"
}

case "${1:-}" in
  --uninstall) uninstall ;;
  --hook) [ -n "${2:-}" ] || { echo "usage: ./install.sh --hook <repo>" >&2; exit 1; }
          install_launcher; install_hook "$2" ;;
  "") install_launcher ;;
  *) echo "usage: ./install.sh [--hook <repo>] [--uninstall]" >&2; exit 1 ;;
esac
